/**
 * AF51-RBX — UIBuilder
 * t3-rbx/ui-builder.js
 *
 * Generates the canonical StarterGui/ structure:
 *   - HUD controller (LocalScript)
 *   - Inventory screen (LocalScript + ModuleScript)
 *   - Shop screen (LocalScript + ModuleScript)
 *   - Notifications system (LocalScript)
 *   - Menus (LocalScript)
 *   - Runtime overlays (ModuleScript)
 *
 * Layer:       T3-RBX / Factory Core
 * Output:      build/src/StarterGui/
 * Governance:  All UI state driven by StateStore.
 *              Direct DataModel mutation from UI FORBIDDEN.
 *
 * Deterministic: same target → same output, byte for byte.
 */

import path from 'node:path';
import * as fs from 'node:fs';

// ── UI system definitions ─────────────────────────────────────────────────

/**
 * Core UI systems — always generated regardless of target type.
 */
const CORE_UI_SYSTEMS = [
  'HUD',
  'Notifications',
  'Menus',
];

/**
 * Per-target-type additional UI systems.
 */
const TARGET_UI_SYSTEMS = {
  obby:      ['Inventory'],
  tycoon:    ['Inventory', 'Shop'],
  simulator: ['Inventory', 'Shop'],
  rpg:       ['Inventory', 'Shop'],
  fps:       [],
};

// ── Luau template generators ──────────────────────────────────────────────

function _header(description, scriptType) {
  const typeComment = {
    local:   'LocalScript',
    server:  'Script',
    module:  'ModuleScript',
  }[scriptType] || 'LocalScript';

  return [
    '--!strict',
    `-- ${description}`,
    `-- [${typeComment}] AF51-RBX | Generated by UIBuilder — DO NOT EDIT`,
    '-- All UI state sourced from StateStore. Direct DataModel mutation FORBIDDEN.',
    '',
  ].join('\n');
}

// ── HUD ───────────────────────────────────────────────────────────────────

function _generateHUDController(targetType) {
  return [
    _header('HUDController — main heads-up display driver', 'local'),
    'local Players    = game:GetService("Players")',
    'local RunService = game:GetService("RunService")',
    '',
    'local Packages = game.ReplicatedStorage.Packages.AF51Runtime',
    'local StateStore   = require(Packages.StateStore)',
    'local EventBus     = require(Packages.EventBus)',
    'local NetworkLayer = require(Packages.NetworkLayer)',
    '',
    'local LocalPlayer = Players.LocalPlayer',
    'local PlayerGui   = LocalPlayer:WaitForChild("PlayerGui")',
    '',
    '-- HUD state cache',
    'local _hudCache: {',
    '\tcoins:  number,',
    '\thealth: number,',
    '\tlevel:  number,',
    '} = { coins = 0, health = 100, level = 1 }',
    '',
    '-- Subscribe to state changes',
    'StateStore.subscribe("ECONOMY", function(domain)',
    `\tif domain and domain.coins ~= nil then`,
    '\t\t_hudCache.coins = domain.coins',
    '\t\t-- TODO: update coin label via ScreenGui reference',
    '\tend',
    'end)',
    '',
    'StateStore.subscribe("PLAYER_PROGRESSION", function(domain)',
    '\tif domain and domain.level ~= nil then',
    '\t\t_hudCache.level = domain.level',
    '\tend',
    'end)',
    '',
    '-- Listen for server-driven HUD events',
    'EventBus.on("ui:hud:update", function(payload)',
    '\tif payload.health ~= nil then',
    '\t\t_hudCache.health = payload.health',
    '\tend',
    'end)',
    '',
    '-- Network: listen for UIToggle remote',
    'NetworkLayer.onClientEvent("UIToggle", function(data)',
    '\tif data and data.panel then',
    '\t\tEventBus.emit("ui:panel:toggle", { panel = data.panel, visible = data.visible })',
    '\tend',
    'end)',
    '',
    `-- Target: ${targetType}`,
    'print("[HUDController] Initialized for target: ' + targetType + '")',
  ].join('\n');
}

// ── Notifications ─────────────────────────────────────────────────────────

function _generateNotificationsController() {
  return [
    _header('NotificationsController — push notification system', 'local'),
    'local Players = game:GetService("Players")',
    '',
    'local Packages = game.ReplicatedStorage.Packages.AF51Runtime',
    'local EventBus     = require(Packages.EventBus)',
    'local NetworkLayer = require(Packages.NetworkLayer)',
    '',
    'local LocalPlayer = Players.LocalPlayer',
    '',
    '-- Notification queue (FIFO)',
    'local _queue: { { message: string, severity: string, duration: number } } = {}',
    'local _showing = false',
    '',
    'local function showNext()',
    '\tif _showing or #_queue == 0 then return end',
    '\t_showing = true',
    '\tlocal notif = table.remove(_queue, 1)',
    '\t-- TODO: drive ScreenGui notification frame',
    '\tEventBus.emit("ui:notification:show", notif)',
    '\ttask.delay(notif.duration, function()',
    '\t\t_showing = false',
    '\t\tshowNext()',
    '\tend)',
    'end',
    '',
    'local function push(message: string, severity: string, duration: number)',
    '\ttable.insert(_queue, {',
    '\t\tmessage  = message,',
    '\t\tseverity = severity or "info",',
    '\t\tduration = duration or 3,',
    '\t})',
    '\tshowNext()',
    'end',
    '',
    '-- Server-driven notifications',
    'NetworkLayer.onClientEvent("NotificationPush", function(data)',
    '\tif data and data.message then',
    '\t\tpush(data.message, data.severity, data.duration)',
    '\tend',
    'end)',
    '',
    '-- Local event-driven notifications',
    'EventBus.on("ui:notify", function(payload)',
    '\tpush(payload.message, payload.severity, payload.duration)',
    'end)',
    '',
    'return { push = push }',
  ].join('\n');
}

// ── Menus ─────────────────────────────────────────────────────────────────

function _generateMenusController() {
  return [
    _header('MenusController — main menu and settings system', 'local'),
    'local Players    = game:GetService("Players")',
    'local UserInputService = game:GetService("UserInputService")',
    '',
    'local Packages = game.ReplicatedStorage.Packages.AF51Runtime',
    'local EventBus = require(Packages.EventBus)',
    '',
    'local LocalPlayer = Players.LocalPlayer',
    '',
    '-- Menu state',
    'local _menuOpen = false',
    '',
    'local function openMenu()',
    '\tif _menuOpen then return end',
    '\t_menuOpen = true',
    '\tEventBus.emit("ui:menu:open", {})',
    'end',
    '',
    'local function closeMenu()',
    '\tif not _menuOpen then return end',
    '\t_menuOpen = false',
    '\tEventBus.emit("ui:menu:close", {})',
    'end',
    '',
    'local function toggleMenu()',
    '\tif _menuOpen then closeMenu() else openMenu() end',
    'end',
    '',
    '-- Escape key toggle',
    'UserInputService.InputBegan:Connect(function(input, processed)',
    '\tif processed then return end',
    '\tif input.KeyCode == Enum.KeyCode.Escape then',
    '\t\ttoggleMenu()',
    '\tend',
    'end)',
    '',
    '-- Panel toggle events from server',
    'EventBus.on("ui:panel:toggle", function(payload)',
    '\tif payload.panel == "menu" then',
    '\t\tif payload.visible then openMenu() else closeMenu() end',
    '\tend',
    'end)',
    '',
    'return { openMenu = openMenu, closeMenu = closeMenu, toggleMenu = toggleMenu }',
  ].join('\n');
}

// ── Inventory ─────────────────────────────────────────────────────────────

function _generateInventoryController() {
  return [
    _header('InventoryController — player inventory UI', 'local'),
    'local Players = game:GetService("Players")',
    '',
    'local Packages = game.ReplicatedStorage.Packages.AF51Runtime',
    'local StateStore = require(Packages.StateStore)',
    'local EventBus   = require(Packages.EventBus)',
    '',
    'local LocalPlayer = Players.LocalPlayer',
    '',
    '-- Inventory UI state',
    'local _open    = false',
    'local _items: { { id: string, name: string, quantity: number } } = {}',
    '',
    '-- Sync from StateStore',
    'StateStore.subscribe("INVENTORY", function(domain)',
    '\tif domain and domain.items then',
    '\t\t_items = domain.items',
    '\t\tEventBus.emit("ui:inventory:refresh", { items = _items })',
    '\tend',
    'end)',
    '',
    'local function openInventory()',
    '\t_open = true',
    '\tEventBus.emit("ui:inventory:open", { items = _items })',
    'end',
    '',
    'local function closeInventory()',
    '\t_open = false',
    '\tEventBus.emit("ui:inventory:close", {})',
    'end',
    '',
    'EventBus.on("ui:panel:toggle", function(payload)',
    '\tif payload.panel == "inventory" then',
    '\t\tif payload.visible then openInventory() else closeInventory() end',
    '\tend',
    'end)',
    '',
    'return { openInventory = openInventory, closeInventory = closeInventory }',
  ].join('\n');
}

// ── Shop ──────────────────────────────────────────────────────────────────

function _generateShopController() {
  return [
    _header('ShopController — in-game shop UI', 'local'),
    'local Players = game:GetService("Players")',
    '',
    'local Packages = game.ReplicatedStorage.Packages.AF51Runtime',
    'local StateStore   = require(Packages.StateStore)',
    'local EventBus     = require(Packages.EventBus)',
    'local NetworkLayer = require(Packages.NetworkLayer)',
    '',
    'local LocalPlayer = Players.LocalPlayer',
    '',
    '-- Shop state',
    'local _open  = false',
    'local _items: { { id: string, name: string, price: number, currency: string } } = {}',
    '',
    'local function refreshShop()',
    '\t-- Fetch shop catalog from server',
    '\tlocal result = NetworkLayer.invokeServer("GetShopItems", {})',
    '\tif result and result.items then',
    '\t\t_items = result.items',
    '\t\tEventBus.emit("ui:shop:refresh", { items = _items })',
    '\tend',
    'end',
    '',
    'local function openShop()',
    '\t_open = true',
    '\trefreshShop()',
    '\tEventBus.emit("ui:shop:open", { items = _items })',
    'end',
    '',
    'local function closeShop()',
    '\t_open = false',
    '\tEventBus.emit("ui:shop:close", {})',
    'end',
    '',
    'local function requestPurchase(itemId: string)',
    '\tif not _open then return end',
    '\tNetworkLayer.fireServer("PurchaseRequest", { itemId = itemId })',
    'end',
    '',
    'NetworkLayer.onClientEvent("PurchaseResult", function(data)',
    '\tEventBus.emit("ui:shop:purchase_result", data)',
    '\tif data.success then',
    '\t\tEventBus.emit("ui:notify", {',
    '\t\t\tmessage  = "Purchase successful: " .. (data.itemName or "item"),',
    '\t\t\tseverity = "success",',
    '\t\t\tduration = 3,',
    '\t\t})',
    '\tend',
    'end)',
    '',
    'EventBus.on("ui:panel:toggle", function(payload)',
    '\tif payload.panel == "shop" then',
    '\t\tif payload.visible then openShop() else closeShop() end',
    '\tend',
    'end)',
    '',
    'return { openShop = openShop, closeShop = closeShop, requestPurchase = requestPurchase }',
  ].join('\n');
}

// ── Runtime overlay module ────────────────────────────────────────────────

function _generateRuntimeOverlay() {
  return [
    _header('RuntimeOverlay — debug/admin overlay module', 'module'),
    '',
    'local RunService = game:GetService("RunService")',
    '',
    'local Packages = game.ReplicatedStorage.Packages.AF51Runtime',
    'local AuditRuntime = require(Packages.AuditRuntime)',
    'local StateStore   = require(Packages.StateStore)',
    '',
    'local RuntimeOverlay = {}',
    '',
    '-- Only visible in Studio',
    'local IS_STUDIO = RunService:IsStudio()',
    '',
    'function RuntimeOverlay.dump()',
    '\tif not IS_STUDIO then',
    '\t\tAuditRuntime.warn("[RuntimeOverlay] dump() called outside Studio — skipped")',
    '\t\treturn',
    '\tend',
    '\tlocal snapshot = StateStore.getState()',
    '\tprint("[RuntimeOverlay] State snapshot:")',
    '\tfor domain, state in pairs(snapshot) do',
    '\t\tprint("  [" .. domain .. "]:", state)',
    '\tend',
    'end',
    '',
    'function RuntimeOverlay.logAuditTail(n: number)',
    '\tif not IS_STUDIO then return end',
    '\tlocal entries = AuditRuntime.tail(n or 20)',
    '\tprint("[RuntimeOverlay] Audit tail (" .. #entries .. " entries):")',
    '\tfor _, e in ipairs(entries) do',
    '\t\tprint("  [" .. e.severity .. "] " .. e.message)',
    '\tend',
    'end',
    '',
    'return RuntimeOverlay',
  ].join('\n');
}

// ── UIBuilder ─────────────────────────────────────────────────────────────

class UIBuilder {

  /**
   * Generate the full StarterGui structure for a target.
   *
   * @param {object} opts
   * @param {string} opts.buildRoot       - path to assembled build dir
   * @param {object} opts.target          - resolved target descriptor
   * @param {object} [opts.auditLedger]
   * @returns {{ ok: boolean, systems: string[], errors: string[] }}
   */
  static build({ buildRoot, target, auditLedger }) {
    const errors     = [];
    const targetType = (target.type || 'obby').toLowerCase();
    const generated  = [];

    const _audit = (level, msg, meta = {}) => {
      if (auditLedger && typeof auditLedger[level] === 'function') {
        auditLedger[level](`[UIBuilder] ${msg}`, {
          source: 'UIBuilder.build',
          targetId: target.id,
          ...meta,
        });
      }
    };

    _audit('info', `Building UI structure for type='${targetType}'`);

    const starterGuiDir = path.join(buildRoot, 'src', 'StarterGui');

    // ── Resolve active UI systems ───────────────────────────────────────
    const extraSystems = TARGET_UI_SYSTEMS[targetType] || [];
    const allSystems   = [...new Set([...CORE_UI_SYSTEMS, ...extraSystems])];

    // ── Generate each system ────────────────────────────────────────────
    const generators = {
      HUD:           () => ({
        dir:   'HUD',
        files: [{ name: 'HUDController.client.lua', content: _generateHUDController(targetType) }],
      }),
      Notifications: () => ({
        dir:   'Notifications',
        files: [{ name: 'NotificationsController.client.lua', content: _generateNotificationsController() }],
      }),
      Menus: () => ({
        dir:   'Menus',
        files: [{ name: 'MenusController.client.lua', content: _generateMenusController() }],
      }),
      Inventory: () => ({
        dir:   'Inventory',
        files: [{ name: 'InventoryController.client.lua', content: _generateInventoryController() }],
      }),
      Shop: () => ({
        dir:   'Shop',
        files: [{ name: 'ShopController.client.lua', content: _generateShopController() }],
      }),
    };

    for (const systemName of allSystems) {
      const gen = generators[systemName];
      if (!gen) {
        errors.push(`Unknown UI system: '${systemName}'`);
        continue;
      }

      const { dir, files } = gen();
      const systemDir = path.join(starterGuiDir, dir);

      try {
        fs.mkdirSync(systemDir, { recursive: true });
      } catch (e) {
        errors.push(`Cannot create dir ${systemDir}: ${e.message}`);
        continue;
      }

      for (const { name, content } of files) {
        try {
          fs.writeFileSync(path.join(systemDir, name), content, 'utf8');
          generated.push(`${dir}/${name}`);
        } catch (e) {
          errors.push(`Failed to write ${name}: ${e.message}`);
        }
      }
    }

    // ── RuntimeOverlay (shared) ─────────────────────────────────────────
    const sharedDir = path.join(starterGuiDir, 'Shared');
    try {
      fs.mkdirSync(sharedDir, { recursive: true });
      fs.writeFileSync(
        path.join(sharedDir, 'RuntimeOverlay.lua'),
        _generateRuntimeOverlay(),
        'utf8'
      );
      generated.push('Shared/RuntimeOverlay.lua');
    } catch (e) {
      errors.push(`RuntimeOverlay.lua write failed: ${e.message}`);
    }

    if (errors.length > 0) {
      return { ok: false, systems: generated, errors };
    }

    _audit('info', `UI build complete: ${generated.length} files across ${allSystems.length} systems`, {
      systems: allSystems,
      files:   generated,
    });

    return { ok: true, systems: allSystems, errors: [] };
  }

  /**
   * Returns the list of UI systems for a given target type.
   *
   * @param {string} targetType
   * @returns {string[]}
   */
  static getSystems(targetType) {
    const t = (targetType || 'obby').toLowerCase();
    return [...new Set([...CORE_UI_SYSTEMS, ...(TARGET_UI_SYSTEMS[t] || [])])];
  }
}

// ── Exports ───────────────────────────────────────────────────────────────

export {

  UIBuilder,
  CORE_UI_SYSTEMS,
  TARGET_UI_SYSTEMS,

};