// t3/Factory/rbx-production/roblox-emitter.js
// AF51-RBX | T3 Layer — RobloxEmitter
// Role  : Serializes the finished SceneGraph to deterministic Luau:
//          - src/ServerScriptService/Scene/AF51SceneBuilder.server.lua
//            (Workspace/AF51Scene/* nodes)
//          - src/ServerScriptService/Scene/AF51Atmosphere.server.lua
//            (Lighting service properties + Lighting/* post-effect children)
//         At Roblox runtime, the server scripts do Instance.new() per node
//         so the world materializes server-side, no extra tooling needed.
//         Also emits top-level production-scenegraph.json and
//         production-quality-report.json — both are on the zip whitelist
//         so they survive ZIP hardening and reach the final capsule.

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const HEADER =
  "--!strict\n" +
  "-- AF51-RBX | Auto-generated by VisualDirector → RobloxEmitter\n" +
  "-- DO NOT EDIT — regenerated on every build, deterministic by target.\n\n";

function _luaValue(v) {
  if (v === null || v === undefined) return "nil";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number")  return Number.isInteger(v) ? String(v) : v.toFixed(3);
  if (typeof v === "string") {
    // If looks like a Luau constructor (Vector3.new, Color3.fromRGB, Enum.*, BrickColor.new),
    // emit verbatim; otherwise quote.
    if (/^(Vector3|Color3|CFrame|UDim2?|Enum\.|BrickColor)/.test(v)) return v;
    return '"' + v.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
  }
  return "nil";
}

// Tags meant for CollectionService get an AddTag call from the Lua builder.
// Convention (v2): tags that start with an uppercase letter are gameplay
// tags surfaced to ObbyKit / TycoonKit / etc.; lowercase tags are pipeline-
// internal (zone:*, layer:*, tier:*, density, landmark, ...) and stay off
// CollectionService.
function _isGameplayTag(tag) {
  return typeof tag === "string" && tag.length > 0 && tag[0] >= "A" && tag[0] <= "Z";
}

function _emitAttributeCall(varName, attrName, value) {
  // SetAttribute supports a fixed subset of types. We only emit scalars.
  if (typeof value === "boolean" || typeof value === "number") {
    return "\t" + varName + ":SetAttribute(\"" + attrName + "\", " + (typeof value === "boolean" ? (value ? "true" : "false") : (Number.isInteger(value) ? String(value) : value.toFixed(3))) + ")";
  }
  if (typeof value === "string") {
    return "\t" + varName + ":SetAttribute(\"" + attrName + "\", \"" + value.replace(/\\/g, "\\\\").replace(/"/g, "\\\"") + "\")";
  }
  return null; // unsupported attribute type — skip silently
}

function _emitNode(node, indexById, sceneVarMap) {
  // parent = "Workspace/AF51Scene" → root scene folder
  //        | "Workspace/AF51Scene/<partName>" → previously-emitted instance
  const lines = [];
  const varName = "n_" + node.id.slice(2);
  lines.push("\tlocal " + varName + " = Instance.new(\"" + node.className + "\")");
  lines.push("\t" + varName + ".Name = " + _luaValue(node.name));

  const propKeys = Object.keys(node.properties).sort();
  for (const k of propKeys) {
    lines.push("\t" + varName + "." + k + " = " + _luaValue(node.properties[k]));
  }

  // Resolve parent
  const parentPath = node.parent;
  if (parentPath === "Workspace/AF51Scene") {
    lines.push("\t" + varName + ".Parent = sceneRoot");
  } else if (parentPath.startsWith("Workspace/AF51Scene/")) {
    const parentName = parentPath.substring("Workspace/AF51Scene/".length);
    const parentVar  = sceneVarMap.get(parentName);
    if (parentVar) {
      lines.push("\t" + varName + ".Parent = " + parentVar);
    } else {
      lines.push("\t" + varName + ".Parent = sceneRoot:FindFirstChild(" + _luaValue(parentName) + ") or sceneRoot");
    }
  } else {
    // unknown parent path → drop into sceneRoot as fallback
    lines.push("\t" + varName + ".Parent = sceneRoot");
  }

  // Roblox instance attributes (gameplay metadata read by Kits via :GetAttribute).
  const attrs = node.attributes || {};
  for (const k of Object.keys(attrs).sort()) {
    const line = _emitAttributeCall(varName, k, attrs[k]);
    if (line) lines.push(line);
  }

  // CollectionService tags — only the uppercase "gameplay" subset. Lowercase
  // tags (zone:*, layer:*, tier:*, density, …) are pipeline-internal and stay
  // out of the runtime so kits don't trip on them.
  const tags = Array.isArray(node.tags) ? node.tags : [];
  for (const t of tags) {
    if (_isGameplayTag(t)) {
      lines.push("\tCollectionService:AddTag(" + varName + ", " + _luaValue(t) + ")");
    }
  }

  sceneVarMap.set(node.name, varName);
  return lines.join("\n");
}

function _emitSceneBuilder(graph) {
  // Only Workspace-rooted nodes — Lighting children are emitted separately.
  const sceneNodes = graph.nodes.filter(
    (n) => n.parent === "Workspace/AF51Scene" || n.parent.startsWith("Workspace/AF51Scene/"),
  );
  const varMap = new Map();
  const body = [];
  body.push(HEADER);
  body.push("local Workspace = game:GetService(\"Workspace\")");
  body.push("local CollectionService = game:GetService(\"CollectionService\")\n");
  body.push("local function build()");
  body.push("\tlocal existing = Workspace:FindFirstChild(\"AF51Scene\")");
  body.push("\tif existing then existing:Destroy() end");
  body.push("\tlocal sceneRoot = Instance.new(\"Folder\")");
  body.push("\tsceneRoot.Name = \"AF51Scene\"");
  body.push("\tsceneRoot.Parent = Workspace\n");

  for (const node of sceneNodes) {
    body.push(_emitNode(node, graph.byId, varMap));
  }

  body.push("\tprint(\"[AF51-RBX] ✓ AF51Scene built (\" .. " +
            sceneNodes.length + " .. \" instances) target=" + graph.targetId + "\")");
  body.push("\treturn sceneRoot");
  body.push("end\n");
  body.push("local ok, err = pcall(build)");
  body.push("if not ok then warn(\"[AF51-RBX] AF51SceneBuilder failed: \" .. tostring(err)) end\n");
  return body.join("\n");
}

// v63 — Per-target Terrain emission. Runs only when graph.services.Terrain
// is populated by TerrainPass. Output is a standalone server script that
// uses workspace.Terrain:FillBlock for each op in order, idempotent via
// a clear-and-fill pattern (so re-running the build replaces, not stacks).
function _emitTerrain(graph) {
  const cfg = graph.services.Terrain;
  if (!cfg || !Array.isArray(cfg.ops) || !cfg.ops.length) return null;
  const body = [];
  body.push(HEADER);
  body.push("local Workspace = game:GetService(\"Workspace\")");
  body.push("local terrain   = Workspace.Terrain\n");
  body.push("local function buildTerrain()");
  // Idempotent: clear existing terrain in a generous bounding box.
  body.push("\tterrain:Clear()");
  for (const op of cfg.ops) {
    body.push("\tterrain:FillBlock(" + op.cframe + ", " + op.size + ", " + op.material + ")");
  }
  body.push("\tprint(\"[AF51-RBX] ✓ Terrain biome=" + cfg.biome + " ops=" + cfg.ops.length + " target=" + graph.targetId + "\")");
  body.push("end\n");
  body.push("local ok, err = pcall(buildTerrain)");
  body.push("if not ok then warn(\"[AF51-RBX] AF51Terrain failed: \" .. tostring(err)) end\n");
  return body.join("\n");
}

function _emitLightingChild(node) {
  // Children of the Lighting service. Each gets a fresh Instance.new() call.
  // Variable name uses the node id so two effects can co-exist deterministically.
  const lines = [];
  const varName = "fx_" + node.id.slice(2);
  lines.push("\tlocal " + varName + " = Instance.new(\"" + node.className + "\")");
  lines.push("\t" + varName + ".Name = " + _luaValue(node.name));
  const propKeys = Object.keys(node.properties).sort();
  for (const k of propKeys) {
    lines.push("\t" + varName + "." + k + " = " + _luaValue(node.properties[k]));
  }
  lines.push("\t" + varName + ".Parent = Lighting");
  return lines.join("\n");
}

function _emitAtmosphere(graph) {
  const lighting = graph.services.Lighting || {};
  const effects  = graph.nodes.filter((n) => n.parent === "Lighting");
  const body = [];
  body.push(HEADER);
  body.push("local Lighting = game:GetService(\"Lighting\")\n");

  // Service-level properties
  const keys = Object.keys(lighting).sort();
  for (const k of keys) {
    body.push("Lighting." + k + " = " + _luaValue(lighting[k]));
  }

  // Post-process effect children (Atmosphere, BloomEffect, ColorCorrectionEffect,
  // SunRaysEffect, DepthOfFieldEffect). Wrapped in pcall'd build so the script
  // is idempotent across re-runs.
  body.push("");
  body.push("local function applyEffects()");
  // Clean previous AF51-prefixed effects to keep re-runs idempotent.
  body.push("\tfor _, child in ipairs(Lighting:GetChildren()) do");
  body.push("\t\tif string.sub(child.Name, 1, 4) == \"AF51\" then child:Destroy() end");
  body.push("\tend");
  for (const node of effects) {
    body.push(_emitLightingChild(node));
  }
  body.push("end");
  body.push("");
  body.push("local ok, err = pcall(applyEffects)");
  body.push("if not ok then warn(\"[AF51-RBX] AF51Atmosphere effects failed: \" .. tostring(err)) end");
  body.push("");
  body.push("print(\"[AF51-RBX] ✓ Atmosphere applied (target=" + graph.targetId +
            ", effects=" + effects.length + ")\")");
  body.push("");
  return body.join("\n");
}

// 1980-01-01 00:00:00 UTC \u2014 deterministic-build epoch shared with
// ZipHardener and LightGhostVault. Used as producedAt when
// RBX_DETERMINISTIC_BUILD=1 so the envelope is byte-stable.
const DETERMINISTIC_EPOCH_MS = 315532800000;

export const RobloxEmitter = {
  async emit({ buildRoot, graph, buildId, deterministic }) {
    // Both server scripts live under ServerScriptService/Scene/ so they fall
    // inside the Rojo tree mapping. The Atmosphere script targets the Lighting
    // service via game:GetService(), it doesn't need to *reside* in Lighting.
    const sceneDir = path.join(buildRoot, "src", "ServerScriptService", "Scene");
    await mkdir(sceneDir, { recursive: true });

    const sceneFile   = path.join(sceneDir, "AF51SceneBuilder.server.lua");
    const lightFile   = path.join(sceneDir, "AF51Atmosphere.server.lua");
    const terrainFile = path.join(sceneDir, "AF51Terrain.server.lua");

    // Top-level metadata \u2014 names match zip-hardener's whitelist so the
    // production scene graph and quality report survive into the final ZIP.
    const sceneGraphFile = path.join(buildRoot, "production-scenegraph.json");
    const qualityFile    = path.join(buildRoot, "production-quality-report.json");

    // Shared production-artifact envelope. Same contract applied by
    // PreviewGenerator to generatedPreview.json so the two files agree
    // on schemaVersion, target, buildId, and producedAt.
    const _det = deterministic === true || (typeof process !== "undefined" && process.env && process.env.RBX_DETERMINISTIC_BUILD === "1");
    const envelope = {
      schemaVersion: "1.1.0",
      kind:          "rbx-scenegraph",
      buildId:       buildId || null,
      target:        graph.targetId,
      producedAt:    _det ? DETERMINISTIC_EPOCH_MS : Date.now(),
    };

    await writeFile(sceneFile,      _emitSceneBuilder(graph),                       "utf8");
    await writeFile(lightFile,      _emitAtmosphere(graph),                         "utf8");
    await writeFile(sceneGraphFile, JSON.stringify(graph.toJSON(envelope), null, 2), "utf8");
    await writeFile(qualityFile,    JSON.stringify(graph.report || {},  null, 2),   "utf8");

    // v63 — Terrain script (only when TerrainPass populated graph.services.Terrain).
    const terrainSrc = _emitTerrain(graph);
    const emittedFiles = [
      path.relative(buildRoot, sceneFile),
      path.relative(buildRoot, lightFile),
      path.relative(buildRoot, sceneGraphFile),
      path.relative(buildRoot, qualityFile),
    ];
    if (terrainSrc) {
      await writeFile(terrainFile, terrainSrc, "utf8");
      emittedFiles.push(path.relative(buildRoot, terrainFile));
    }

    return { ok: true, files: emittedFiles };
  },
};

export default RobloxEmitter;
